language: node_js
node_js:
  - "14"
cache:
  directories:
    - "node_modules"

env:
  - CI=true

before_deploy:
  - npm install netlify-cli netlify-lambda -g
  - "npm run build && cp dist/index.html dist/200.html"
  - netlify-lambda build functions/src

deploy:
  provider: script
  script: netlify deploy --site=$NETLIFY_SITEID --auth=$NETLIFY_TOKEN --prod
  skip_cleanup: true
  on:
    branch: master
