language: node_js
node_js:
  - "11"
cache:
  directories:
    - "node_modules"

env:
  - CI=true

before_deploy:
  - npm install netlify-cli -g
  - "npm run build && cp dist/index.html dist/200.html"

deploy:
  provider: script
  script: netlify deploy --site=$NETLIFY_SITEID --auth=$NETLIFY_TOKEN --dir=dist --prod
  skip_cleanup: true
  on:
    branch: master