[build]
  base = "."
  publish = "dist/"
  command = "npm run build"
  functions = "functions/src/"

  [build.environment]
    NODE_VERSION = "20"
    AWS_LAMBDA_JS_RUNTIME = "nodejs20.x"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
